version: '3'

services:
  lab1-rest-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
    ports:
      - "5000:5000"
    command: python app.py
